import "./globals.css";
import type { Metadata } from "next";
import NextAuthProvider from "./providers/nextAuth";

export const metadata: Metadata = {
  title: "Mirrorld",
  description: "Generated by お笑い向上委員会",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body>
        <NextAuthProvider>{children}</NextAuthProvider>
      </body>
    </html>
  );
}
